version: "3.9"

services:
  databse:
   image: postgres
   container_name: todosImage
   restart: always
   ports: 
     - 5432:5432
   environment:
     - POSTGRES_USER=admin
     - POSTGRES_PASSWORD=admin
     - POSTGRES_DB=databse
   volumes:
    - pgdata:/data/postgres  

volumes:
  pgdata:
   driver: local